### PR TITLE
Revise CI setup for integration tests

### LINKED ISSUE #343: Run tests with PostgreSQL
Currently, the CI runs all the tests the tests with sqlite as db backend. This is just the default from the development setup.
This setup has the severe drawback that any PostgreSQL specifics will never be tested.
The convenience of sqlite for the development setup is still quite nice, but maybe we can setup things in a way such that the PostgreSQL backend (ideally with the same version as the external production DB) _can_ be easily enabled.
With this, we should run all the tests in the CI with PostgreSQL, at the minimum for the jobs integration and upgrade_integration.

### PR DESCRIPTION
**Pull request by matzf**
* General cleanup: move lengthy snippets from .circleci/config.yaml into separate shell scripts. This makes the setup less cluttered and makes easier to run this setup locally. Also, this has some impact for the upgrade tests (see below).
* Run integration / upgrade integration tests with PostgreSQL database. Fixes #343.
* Include more ASes in the integration test network. In particular, include the nodes related to the VPN link to the test User AS in the first, normal run instead of keeping this separate. The test network now includes an additional core link. So, this gives a broader test and makes the setup simpler. The only downside is that it possibly makes it harder to diagnose issues specifically related to OpenVPN -- I'm hoping that the VPN stuff will just keep working, so this seems ok to me.
* Upgrade integration tests are now triggered with a manual approval step instead of a branch name filter.
* Upgrade integration tests now use the script files from the old code version to setup the containers etc. The hope is that this allows to paper over some incompatible changes in the setup and allow running the upgrade tests without manual tweaks to the circleci config, e.g. for changes like using `scion ping` instead of `scmp echo`.
* Export SCION service logs in artifacts. Replaces #325.
* Separate "workflow" for each "job". This makes the github UI show the individual sub-tests. Also, split style check from unit tests.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/355)

### CODE REVIEW

**Review by cmeury — APPROVED** [review]
Maybe run shellcheck on all the new files to have a somewhat consistent style?

> Reviewed 31 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/355#-:-MRdJjEJ9PLwW9wwd-L1:b-cm15qw)* status: all files reviewed, 9 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[.circleci/config.yml, line 304 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/355#-MRdF7dl6A099dvJn8Tg:-MRdF7dmE6rRd9t6h-69:bwwhz86) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e930403a4ec6c1f972a5452a6a31147147e5e40a/.circleci/config.yml#L304)):*
> Upgrade integration tests are now triggered with a manual approval step instead of a branch name filter.

It seems like this causes the workflow to be in status "On Hold" on CircleCI and blocking the PR on GitHub.
___
*[.circleci/django-ci-entrypoint.sh, line 1 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/355#-MRdFkb380RpeJ4R3mTX:-MRdFkb380RpeJ4R3mTY:b-xawzsj) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e930403a4ec6c1f972a5452a6a31147147e5e40a/.circleci/django-ci-entrypoint.sh#L1)):*
> ```Shell
> #!/bin/sh
> ```

Missing this huge ETH copyright header as in the other scripts. 
___
*[.circleci/docker-compose.yml, line 90 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/355#-MRdGYo5EVfG4n6R2BQD:-MRdGYo5EVfG4n6R2BQE:b-5j8b1b) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa5a0986e4fa9bd267cd21907e59fa6abcf033fb/.circleci/docker-compose.yml#L90)):*
> ```YAML
>       dockerfile: .circleci/Dockerfile-scionHost
>     depends_on:
>       - as1405
> ```

Why could this and the above one be removed?
___
*[.circleci/scripts/ping-all.sh, line 32 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/355#-MRdH8pzAIWCFhp_4Hxs:-MRdH8pzAIWCFhp_4Hxt:b-72cbw8) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e930403a4ec6c1f972a5452a6a31147147e5e40a/.circleci/scripts/ping-all.sh#L32)):*
> ```Shell
> set -x
> for dstIA in ${ias[@]}; do
>   chronic scion ping -c 1 "$dstIA,127.0.0.1"
> ```

Awesome idea to hide successful output with `chronic`!
___
*[.circleci/setup/build-containers.sh, line 1 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/355#-MRdHDAW2QePItZ5akpV:-MRdHDAW2QePItZ5akpW:b-ely0t3) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e930403a4ec6c1f972a5452a6a31147147e5e40a/.circleci/setup/build-containers.sh#L1)):*
> ```Shell
> # Copyright 2020 ETH Zurich
> ```

Missing shebang
___
*[.circleci/setup/check-scion-connectivity.sh, line 1 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/355#-MRdHI3_2H74ONA6Xq5W:-MRdHI3_2H74ONA6Xq5X:b-ely0t3) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e930403a4ec6c1f972a5452a6a31147147e5e40a/.circleci/setup/check-scion-connectivity.sh#L1)):*
> ```Shell
> # Copyright 2020 ETH Zurich
> ```

Missing shebang
___
*[.circleci/setup/check-scion-connectivity.sh, line 20 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/355#-MRdHe0SErqw05N7wfEs:-MRdHe0SErqw05N7wfEt:b917fyi) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e930403a4ec6c1f972a5452a6a31147147e5e40a/.circleci/setup/check-scion-connectivity.sh#L20)):*
> ```Shell
> 
> set -x
> sleep 5  # Give the services enough time to start (or fail)
> ```

I had to increase that a bit because I saw it fail. But yeah, maybe we can try with 5 seconds again until we observe failures.
___
*[.circleci/setup/check-scion-connectivity.sh, line 22 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/355#-MRdHoj25w3GLffZGnBv:-MRdHoj25w3GLffZGnBw:b-uctt51) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e930403a4ec6c1f972a5452a6a31147147e5e40a/.circleci/setup/check-scion-connectivity.sh#L22)):*
> ```Shell
> sleep 5  # Give the services enough time to start (or fail)
> for c in $containers; do
>   docker-compose exec -T $c check-scion-status.sh
> ```

`"$c"`?
___
*[.circleci/setup/init-coord.sh, line 1 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/355#-MRdIi-38qsRGY5N1AOn:-MRdIi-38qsRGY5N1AOo:b-ely0t3) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e930403a4ec6c1f972a5452a6a31147147e5e40a/.circleci/setup/init-coord.sh#L1)):*
> ```Shell
> # Copyright 2020 ETH Zurich
> ```

Missing shebang

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/355)* status: 23 of 32 files reviewed, 9 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[.circleci/config.yml, line 304 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/355#-MRdF7dl6A099dvJn8Tg:-MRdU40gAV8bbz5pSrXx:b-qg9tes) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e930403a4ec6c1f972a5452a6a31147147e5e40a/.circleci/config.yml#L304)):*
<details><summary><i>Previously, cmeury (Cedric Meury) wrote…</i></summary><blockquote>

> Upgrade integration tests are now triggered with a manual approval step instead of a branch name filter.

It seems like this causes the workflow to be in status "On Hold" on CircleCI and blocking the PR on GitHub.
</blockquote></details>

We can set "upgrade-tests" to not required in the branch protection settings. This should not block the PR on GitHub. It's still not super great, as the GitHub UI shows the step as "pending" instead of explicitly showing that it requires manual approval and the approval button is rather hard to find. But at least the UI reminds us that this step exists. so I still think this is better than the previous approach with branch names.
A different approach to achieve this on circleci could be to use pipeline parameters; I even found an example for this, here: https://iosmith.com/circleci-on-demand-jobs/. I guess this would show up better in the GitHub UI (no pending job). The problem is only that (unlike e.g. gitlabCI or jenkins) circleci does not have a button in the UI to trigger jobs with parameters, only the API can do this. Meh.

Btw. the simplest alternative would be to just run always run this step.
___
*[.circleci/django-ci-entrypoint.sh, line 1 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/355#-MRdFkb380RpeJ4R3mTX:-MRdYdRg1pGhuXNwyJ5U:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e930403a4ec6c1f972a5452a6a31147147e5e40a/.circleci/django-ci-entrypoint.sh#L1)):*
<details><summary><i>Previously, cmeury (Cedric Meury) wrote…</i></summary><blockquote>

Missing this huge ETH copyright header as in the other scripts. 
</blockquote></details>

Done.
___
*[.circleci/docker-compose.yml, line 90 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/355#-MRdGYo5EVfG4n6R2BQD:-MRdYicfCblZWUQMubRb:bfytzv0) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa5a0986e4fa9bd267cd21907e59fa6abcf033fb/.circleci/docker-compose.yml#L90)):*
<details><summary><i>Previously, cmeury (Cedric Meury) wrote…</i></summary><blockquote>

Why could this and the above one be removed?
</blockquote></details>

It wasn't really used. The depends_on only defines a startup and shutdown order and ensures that the dependencies are started when explicitly starting a service, e.g. `docker-compose up useras4` would have started the two above.
Here the entrypoint of the containers is only systemd there is really no need to order this at all. It seemed pointless & potentially confusing.
___
*[.circleci/setup/build-containers.sh, line 1 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/355#-MRdHDAW2QePItZ5akpV:-MRd_cIQ2XAVNQ3eAWkv:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e930403a4ec6c1f972a5452a6a31147147e5e40a/.circleci/setup/build-containers.sh#L1)):*
<details><summary><i>Previously, cmeury (Cedric Meury) wrote…</i></summary><blockquote>

Missing shebang
</blockquote></details>

Done.
___
*[.circleci/setup/check-scion-connectivity.sh, line 1 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/355#-MRdHI3_2H74ONA6Xq5W:-MRd_ct35namhwsLuZbG:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e930403a4ec6c1f972a5452a6a31147147e5e40a/.circleci/setup/check-scion-connectivity.sh#L1)):*
<details><summary><i>Previously, cmeury (Cedric Meury) wrote…</i></summary><blockquote>

Missing shebang
</blockquote></details>

Done.
___
*[.circleci/setup/check-scion-connectivity.sh, line 20 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/355#-MRdHe0SErqw05N7wfEs:-MRd_nLS5rZ8PLXywRbB:b-uz47d0) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e930403a4ec6c1f972a5452a6a31147147e5e40a/.circleci/setup/check-scion-connectivity.sh#L20)):*
<details><summary><i>Previously, cmeury (Cedric Meury) wrote…</i></summary><blockquote>

I had to increase that a bit because I saw it fail. But yeah, maybe we can try with 5 seconds again until we observe failures.
</blockquote></details>

Ok, probably not worth it then, I'll just keep it at 10s.
___
*[.circleci/setup/check-scion-connectivity.sh, line 22 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/355#-MRdHoj25w3GLffZGnBv:-MRd_dooENA1UwzmBSQw:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e930403a4ec6c1f972a5452a6a31147147e5e40a/.circleci/setup/check-scion-connectivity.sh#L22)):*
<details><summary><i>Previously, cmeury (Cedric Meury) wrote…</i></summary><blockquote>

`"$c"`?
</blockquote></details>

Done.
___
*[.circleci/setup/init-coord.sh, line 1 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/355#-MRdIi-38qsRGY5N1AOn:-MRd_fBJ7p6fYuq8Mvz-:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e930403a4ec6c1f972a5452a6a31147147e5e40a/.circleci/setup/init-coord.sh#L1)):*
<details><summary><i>Previously, cmeury (Cedric Meury) wrote…</i></summary><blockquote>

Missing shebang
</blockquote></details>

Done.

**Review by cmeury — APPROVED** [review]
> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/355)* status: all files reviewed, 3 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[.circleci/docker-compose.yml, line 90 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/355#-MRdGYo5EVfG4n6R2BQD:-MRxtJecDWih7bKp62GI:b-1exl7h) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa5a0986e4fa9bd267cd21907e59fa6abcf033fb/.circleci/docker-compose.yml#L90)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

It wasn't really used. The depends_on only defines a startup and shutdown order and ensures that the dependencies are started when explicitly starting a service, e.g. `docker-compose up useras4` would have started the two above.
Here the entrypoint of the containers is only systemd there is really no need to order this at all. It seemed pointless & potentially confusing.
</blockquote></details>

Understood, thanks for the clarification.

**Review by cmeury — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/355)* status: all files reviewed, 2 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[.circleci/config.yml, line 304 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/355#-MRdF7dl6A099dvJn8Tg:-MRxtknhALRYwG-KFrib:b-2jz00k) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e930403a4ec6c1f972a5452a6a31147147e5e40a/.circleci/config.yml#L304)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

We can set "upgrade-tests" to not required in the branch protection settings. This should not block the PR on GitHub. It's still not super great, as the GitHub UI shows the step as "pending" instead of explicitly showing that it requires manual approval and the approval button is rather hard to find. But at least the UI reminds us that this step exists. so I still think this is better than the previous approach with branch names.
A different approach to achieve this on circleci could be to use pipeline parameters; I even found an example for this, here: https://iosmith.com/circleci-on-demand-jobs/. I guess this would show up better in the GitHub UI (no pending job). The problem is only that (unlike e.g. gitlabCI or jenkins) circleci does not have a button in the UI to trigger jobs with parameters, only the API can do this. Meh.

Btw. the simplest alternative would be to just run always run this step.
</blockquote></details>

Ah, ok, the method if changing the branch protection settings seems alright!

**Review by cmeury — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/355)* status: all files reviewed, 2 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

**Review by FR4NK-W — COMMENTED** [review]
> Reviewed 1 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/355)* status: all files reviewed, 3 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[.circleci/setup/check-scion-connectivity.sh, line 18 at r3](https://reviewable.io/reviews/netsec-ethz/scionlab/355#-MS3YvEC9M9rBx6DLZzU:-MS3YvEC9M9rBx6DLZzV:bwrap9f) ([raw file](https://github.com/netsec-ethz/scionlab/blob/b3e9e9fac4e2e53b8fb29a6de59cba390b514449/.circleci/setup/check-scion-connectivity.sh#L18)):*
> ```
> grep -v coord
> ```


Including the ASes that run a CS instead of excluding the coord containers would make more sense, e.g. grepping for the `as` or `useras` prefix and numeric suffix.
I'd also have the status check, await beacons and ping-all be separate functions in this file instead of being in separate scripts.

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/355)* status: 28 of 32 files reviewed, 3 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[.circleci/config.yml, line 304 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/355#-MRdF7dl6A099dvJn8Tg:-MS3ivBQCi1MXXR6DyuD:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e930403a4ec6c1f972a5452a6a31147147e5e40a/.circleci/config.yml#L304)):*
<details><summary><i>Previously, cmeury (Cedric Meury) wrote…</i></summary><blockquote>

Ah, ok, the method if changing the branch protection settings seems alright!
</blockquote></details>

Done.
___
*[.circleci/setup/check-scion-connectivity.sh, line 18 at r3](https://reviewable.io/reviews/netsec-ethz/scionlab/355#-MS3YvEC9M9rBx6DLZzU:-MS3gXiQ2FntdqAWdwd_:b-x7pzoe) ([raw file](https://github.com/netsec-ethz/scionlab/blob/b3e9e9fac4e2e53b8fb29a6de59cba390b514449/.circleci/setup/check-scion-connectivity.sh#L18)):*
> Including the ASes that run a CS instead of excluding the coord containers would make more sense, e.g. grepping for the as or useras prefix and numeric suffix.

Done.

Won't combine the individual checks into one script -- note that defining these steps as bash functions in _this_ script is not possible because they need to run in the individual containers. So the alternative is to directly implement everything in the `docker-compose exec` commands here, which makes this unwieldy for these not-quite-a-single-liner scripts.

**Review by cmeury — APPROVED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/355)* status: all files reviewed, 1 unresolved discussion / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

**Review by FR4NK-W — COMMENTED** [review]
> Reviewed 12 of 31 files at r1, 4 of 9 files at r2, 2 of 2 files at r3, 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/355)* status: all files reviewed, 1 unresolved discussion / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

**Pull request merged**
