### PR TITLE
List users email

### PR DESCRIPTION
**Pull request by juagargi**
Adds a command to list the users email addresses and send them an email.
To be used for service announcements.

- [x] Rebase and merge after #445 is merged

- - -
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/446)

### CODE REVIEW

**Review by FR4NK-W — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/446)* status: 0 of 10 files reviewed, 5 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`scionlab/management/commands/mass_email.py` line 27 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/446#-NbZJ4Ph-d1LK5ER3E8l:-NbZJ4Ph-d1LK5ER3E8m:undefined) ([raw file](https://github.com/netsec-ethz/scionlab/blob/b5fd7b976c4501c7910fd86c7d5db53af1f24385/scionlab/management/commands/mass_email.py#L27)):*
> ```Python
> 
> class Command(BaseCommand):
>     help = 'List the unique emails of the users in alphabetical order'
> ```





_Suggestion:_
```Python
List or send a message to
```
___
*[`scionlab/management/commands/mass_email.py` line 38 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/446#-NbZINwjCxG2OiYWl7b4:-NbZINwjCxG2OiYWl7b5:b-mo4zh0) ([raw file](https://github.com/netsec-ethz/scionlab/blob/b5fd7b976c4501c7910fd86c7d5db53af1f24385/scionlab/management/commands/mass_email.py#L38)):*
>destinataries

recipients ?
___
*[`scionlab/management/commands/mass_email.py` line 59 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/446#-NbZJlE44un0lmXS7NuJ:-NbZJlE44un0lmXS7NuK:bhchnd5) ([raw file](https://github.com/netsec-ethz/scionlab/blob/b5fd7b976c4501c7910fd86c7d5db53af1f24385/scionlab/management/commands/mass_email.py#L59)):*
> is_anonymous

This is always going to be false here
___
*[`scionlab/management/commands/mass_email.py` line 61 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/446#-NbZK6_m3ZLZ9WXvzh8-:-NbZK6_m3ZLZ9WXvzh80:b-bci9c6) ([raw file](https://github.com/netsec-ethz/scionlab/blob/b5fd7b976c4501c7910fd86c7d5db53af1f24385/scionlab/management/commands/mass_email.py#L61)):*
>is_authenticated

This is always going to be true here
___
*[`scionlab/management/commands/mass_email.py` line 73 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/446#-NbZKRn39HphCXOVWpry:-NbZKRn39HphCXOVWprz:undefined) ([raw file](https://github.com/netsec-ethz/scionlab/blob/b5fd7b976c4501c7910fd86c7d5db53af1f24385/scionlab/management/commands/mass_email.py#L73)):*
> ```Python
> 
>     def send(self, **kwargs):
>         print('send email')
> ```





_Suggestion:_
```Python
print('sending email(s)')
```

**Review by juagargi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/446)* status: 0 of 10 files reviewed, 5 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`scionlab/management/commands/mass_email.py` line 27 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/446#-NbZJ4Ph-d1LK5ER3E8l:-NbtEjx8DlPJMiBoh9yU:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/b5fd7b976c4501c7910fd86c7d5db53af1f24385/scionlab/management/commands/mass_email.py#L27)):*
> ```Python
> 
> class Command(BaseCommand):
>     help = 'List the unique emails of the users in alphabetical order'
> ```

Done.
___
*[`scionlab/management/commands/mass_email.py` line 38 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/446#-NbZINwjCxG2OiYWl7b4:-NbtErYq-18s4-g3L1ys:b-gzp383) ([raw file](https://github.com/netsec-ethz/scionlab/blob/b5fd7b976c4501c7910fd86c7d5db53af1f24385/scionlab/management/commands/mass_email.py#L38)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

>destinataries

recipients ?
</blockquote></details>

Done. Replaced all in file.
___
*[`scionlab/management/commands/mass_email.py` line 59 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/446#-NbZJlE44un0lmXS7NuJ:-NbtG6j_ArFRCj0rLvaF:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/b5fd7b976c4501c7910fd86c7d5db53af1f24385/scionlab/management/commands/mass_email.py#L59)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

> is_anonymous

This is always going to be false here
</blockquote></details>

Done.
___
*[`scionlab/management/commands/mass_email.py` line 61 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/446#-NbZK6_m3ZLZ9WXvzh8-:-NbtG8-gD3RpIISDMjpp:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/b5fd7b976c4501c7910fd86c7d5db53af1f24385/scionlab/management/commands/mass_email.py#L61)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

>is_authenticated

This is always going to be true here
</blockquote></details>

Done.
___
*[`scionlab/management/commands/mass_email.py` line 73 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/446#-NbZKRn39HphCXOVWpry:-NbtGDlr4SuOMEEXe-i9:b-852fs1) ([raw file](https://github.com/netsec-ethz/scionlab/blob/b5fd7b976c4501c7910fd86c7d5db53af1f24385/scionlab/management/commands/mass_email.py#L73)):*
> ```Python
> 
>     def send(self, **kwargs):
>         print('send email')
> ```

Done (leftover)

**Review by FR4NK-W — APPROVED** [review]
:lgtm:

> Reviewed 1 of 10 files at r1, 1 of 1 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/446#-:-Nc1hZtt6eBHj9szXL4k:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`scionlab/management/commands/mass_email.py` line 55 at r3](https://reviewable.io/reviews/netsec-ethz/scionlab/446#-Nc1grZy05w2TR1LzKmY:-Nc1grZy05w2TR1LzKmZ:bk88gx7) ([raw file](https://github.com/netsec-ethz/scionlab/blob/d4dd51752a64d4195b0c8efc2d3c18d851182361/scionlab/management/commands/mass_email.py#L55)):*
> ```Python
>         # report user stats:
>         anon = []
>         unauth = []
> ```

Left overs
___
*[`scionlab/management/commands/mass_email.py` line 64 at r3](https://reviewable.io/reviews/netsec-ethz/scionlab/446#-Nc1h0SE5-1KbCw_kVLg:-Nc1h0SE5-1KbCw_kVLh:bb7od0r) ([raw file](https://github.com/netsec-ethz/scionlab/blob/d4dd51752a64d4195b0c8efc2d3c18d851182361/scionlab/management/commands/mass_email.py#L64)):*
> ```Python
>                 active.append(u)
>         print(f'--------------------------- anonymous: {len(anon)}')
>         print(f'--------------------------- unauthorized: {len(unauth)}')
> ```

same

**Review by FR4NK-W — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/446)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`scionlab/management/commands/mass_email.py` line 55 at r5](https://reviewable.io/reviews/netsec-ethz/scionlab/446#-NcRXZQJ5rP06t_zWALE:-NcRXZQKBHUHIZgkuX3i:b-yrumkl) ([raw file](https://github.com/netsec-ethz/scionlab/blob/5cc20bbe2256a45b995220117d513d2c16080095/scionlab/management/commands/mass_email.py#L55)):*
> ```Python
>         # report user stats:
>         anon = []
>         unauth = []
> ```

Unused
___
*[`scionlab/management/commands/mass_email.py` line 64 at r5](https://reviewable.io/reviews/netsec-ethz/scionlab/446#-NcRXarNECw6T_aIv-Kb:-NcRXarNECw6T_aIv-Kc:undefined) ([raw file](https://github.com/netsec-ethz/scionlab/blob/5cc20bbe2256a45b995220117d513d2c16080095/scionlab/management/commands/mass_email.py#L64)):*
> ```Python
>                 active.append(u)
>         print(f'--------------------------- anonymous: {len(anon)}')
>         print(f'--------------------------- unauthorized: {len(unauth)}')
> ```

**Review by FR4NK-W — APPROVED** [review]
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/446)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
