### PR TITLE
 Vagrantfile: fixes for updates and cleanup 

### LINKED ISSUE #296: cronjob in the VMs failed to update the packages
The cronjob in the VMs failed to update the packages. The problem seems to be that `PATH` is not set up normally" (no `/sbin`) in the crontab environment and `dpkg` can't/refuses to run without `ldconfig` and `start-stop-daemon`.

See also: https://askubuntu.com/questions/938359/apt-get-install-remove-update-upgrade-via-cron-job

### PR DESCRIPTION
**Pull request by matzf**
* updates: the crontab entry was broken (#296). Use the unattended-upgrades for this, too.
* initial setup: upgrade all system packages, install `ca-certificates` for the https transport for the scionlab packages (as described in our own docs)
* time sync: 
  * drop messing with the virtualbox-guest-utils to disable guest time sync; I couldn't find a reason to do this, the `GetHostTimeDisabled` seems to work just fine
  * use systemd-timesyncd instead of ntp, as this appears to work just as well and requires fewer magic settings
* drop the port forwarding for the dispatcher port. Only seems to make sense for setups where the VM is one of multiple end hosts in the AS. Such a setup would require a fair bit of tweaking of various config files, so I think it's fair to assume that anybody who wants this is capable of adding the port forwarding rule themselves.
* this stuff is so dense; use a proper template for the Vagrantfile, to allow adding comments for ourselves. After some hair-pulling because django templates refuse to not mess up whitespace, I decided to use jinja2 instead. (c.f. https://code.djangoproject.com/ticket/2594#comment:58)

Fixes #296

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/314)

### CODE REVIEW

**Review by FR4NK-W — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/314)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @matzf)

___
*[scionlab/hostfiles/Vagrantfile.tmpl, line 87 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/314#-MLMd-gsE9g6E_VtSZ6H:-MLMd-gsE9g6E_VtSZ6I:bui9j9q) ([raw file](https://github.com/netsec-ethz/scionlab/blob/48ab1ac6c0d46639219be90f2d7355e09e1c9e06/scionlab/hostfiles/Vagrantfile.tmpl#L87)):*
> ```
> 19:00
> ```
That's new, right? Maybe mention it in the PR description.
___
*[scionlab/hostfiles/Vagrantfile.tmpl, line 88 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/314#-MLMawd796cRPCNM0fg3:-MLMawd796cRPCNM0fg4:b-juy7a4) ([raw file](https://github.com/netsec-ethz/scionlab/blob/48ab1ac6c0d46639219be90f2d7355e09e1c9e06/scionlab/hostfiles/Vagrantfile.tmpl#L88)):*
> ```
> RandomizedDealySec
> ```
Typo
I understand not wanting a large randomized delay, but 5 minutes should be fine, as long as there is no overlap, right?
___
*[scionlab/hostfiles/Vagrantfile.tmpl, line 95 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/314#-MLMb1BwBoMZ1REzvMH9:-MLMb1BwBoMZ1REzvMHA:b-vo7kgf) ([raw file](https://github.com/netsec-ethz/scionlab/blob/48ab1ac6c0d46639219be90f2d7355e09e1c9e06/scionlab/hostfiles/Vagrantfile.tmpl#L95)):*
> ```
> 'RandomizedDealySec=0'
> ```
Typo
___
*[scionlab/tests/data/test_config_tar/user_as_16.yml, line 45 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/314#-MLMcrrg9-JWhswd9Vqy:-MLMcrrg9-JWhswd9Vqz:b5k70mo) ([raw file](https://github.com/netsec-ethz/scionlab/blob/48ab1ac6c0d46639219be90f2d7355e09e1c9e06/scionlab/tests/data/test_config_tar/user_as_16.yml#L45)):*
> ```
> OnCalendar=
> ```
Why do we reset the list of timers? To override the default?

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/314)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @FR4NK-W)

___
*[scionlab/hostfiles/Vagrantfile.tmpl, line 87 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/314#-MLMd-gsE9g6E_VtSZ6H:-MLN3PnMDtUodP7Dmnmv:b2nhll9) ([raw file](https://github.com/netsec-ethz/scionlab/blob/48ab1ac6c0d46639219be90f2d7355e09e1c9e06/scionlab/hostfiles/Vagrantfile.tmpl#L87)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

> ```
> 19:00
> ```
That's new, right? Maybe mention it in the PR description.
</blockquote></details>

Ok.
___
*[scionlab/hostfiles/Vagrantfile.tmpl, line 88 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/314#-MLMawd796cRPCNM0fg3:-MLN3Z2P09yrN6xUTleH:bkr71m4) ([raw file](https://github.com/netsec-ethz/scionlab/blob/48ab1ac6c0d46639219be90f2d7355e09e1c9e06/scionlab/hostfiles/Vagrantfile.tmpl#L88)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

> ```
> RandomizedDealySec
> ```
Typo
I understand not wanting a large randomized delay, but 5 minutes should be fine, as long as there is no overlap, right?
</blockquote></details>

:boom: Thanks, fixed.

Ok, returning the question: is there a reason why you would prefer the delay? To reduce load on the package server? I'm not too worried ;)
I also came across this post, hinting at some weird issues with the RandomizedDelay: https://askubuntu.com/questions/1241078/systemd-persistent-timers-do-not-work-as-expected -- I didn't look into it at all, so perhaps it's no concern, but it leaves a me preferring not enable this if we don't need it.
___
*[scionlab/hostfiles/Vagrantfile.tmpl, line 95 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/314#-MLMb1BwBoMZ1REzvMH9:-MLNrjrgDFTuxaFWDBee:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/48ab1ac6c0d46639219be90f2d7355e09e1c9e06/scionlab/hostfiles/Vagrantfile.tmpl#L95)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

> ```
> 'RandomizedDealySec=0'
> ```
Typo
</blockquote></details>

Done.
___
*[scionlab/tests/data/test_config_tar/user_as_16.yml, line 45 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/314#-MLMcrrg9-JWhswd9Vqy:-MLN5NDoB6xx3BrkEtCY:bundyg2) ([raw file](https://github.com/netsec-ethz/scionlab/blob/48ab1ac6c0d46639219be90f2d7355e09e1c9e06/scionlab/tests/data/test_config_tar/user_as_16.yml#L45)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

> ```
> OnCalendar=
> ```
Why do we reset the list of timers? To override the default?
</blockquote></details>

Yes. Added a comment.

**Review by FR4NK-W — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/314)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[scionlab/hostfiles/Vagrantfile.tmpl, line 88 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/314#-MLMawd796cRPCNM0fg3:-MLNw786-ioYStXdtwKA:bu6f0a2) ([raw file](https://github.com/netsec-ethz/scionlab/blob/48ab1ac6c0d46639219be90f2d7355e09e1c9e06/scionlab/hostfiles/Vagrantfile.tmpl#L88)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

:boom: Thanks, fixed.

Ok, returning the question: is there a reason why you would prefer the delay? To reduce load on the package server? I'm not too worried ;)
I also came across this post, hinting at some weird issues with the RandomizedDelay: https://askubuntu.com/questions/1241078/systemd-persistent-timers-do-not-work-as-expected -- I didn't look into it at all, so perhaps it's no concern, but it leaves a me preferring not enable this if we don't need it.
</blockquote></details>

Yeah, I think the main reason for the delay would be to distribute the load ;-)

That link mentions an issue in combination with`Persistent=True`. We don't want the timers to be persistent, or do we?
The default value for RandomizedDelaySec is 0, apt-daily sets it to 12h which I agree makes it quite unpredictable and hard to test.
It also sets Persistent to true, so we'd have to override that as well if we don't want timers to catch up after reboots.

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/314)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @FR4NK-W)

___
*[scionlab/hostfiles/Vagrantfile.tmpl, line 88 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/314#-MLMawd796cRPCNM0fg3:-MLO5Axf7DF6yeXKKo_G:b-leodwq) ([raw file](https://github.com/netsec-ethz/scionlab/blob/48ab1ac6c0d46639219be90f2d7355e09e1c9e06/scionlab/hostfiles/Vagrantfile.tmpl#L88)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

Yeah, I think the main reason for the delay would be to distribute the load ;-)

That link mentions an issue in combination with`Persistent=True`. We don't want the timers to be persistent, or do we?
The default value for RandomizedDelaySec is 0, apt-daily sets it to 12h which I agree makes it quite unpredictable and hard to test.
It also sets Persistent to true, so we'd have to override that as well if we don't want timers to catch up after reboots.
</blockquote></details>

I was assuming that we want the timer to be persistent, yes. If a VM boots up after being down for some time, it should check for updates immediately, right? Or why not?

**Comment by matzf** [comment]
Note: before reactivating this, check how important accurate time synchronisation even is now (for scionlab). It appears there are no more explicit timestamp checks for paths.

**Review by cmeury — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 1 of 1 files at r2, 1 of 4 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/314)* status: all files reviewed, 1 unresolved discussion / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

**Comment by cmeury** [comment]
Rebased against current master, fixed small things & tested the Vagrant file in testdata locally. Seems good to me.

**Review by FR4NK-W — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/314)* status: all files reviewed, 1 unresolved discussion / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[scionlab/hostfiles/Vagrantfile.tmpl, line 88 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/314#-MLMawd796cRPCNM0fg3:-MQWMaxWCbC38mKxAkzk:b-351dpu) ([raw file](https://github.com/netsec-ethz/scionlab/blob/48ab1ac6c0d46639219be90f2d7355e09e1c9e06/scionlab/hostfiles/Vagrantfile.tmpl#L88)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

I was assuming that we want the timer to be persistent, yes. If a VM boots up after being down for some time, it should check for updates immediately, right? Or why not?
</blockquote></details>

To not break VMs by premature updates during SCION version updates, since to me it seemed that during previous updates we used the VM update time as "synchonisation point".
But directly using the repo package release time make more sense anyway, so :thumbsup: if that is the working assumption

**Review by FR4NK-W — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/314)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by cmeury** [comment]
Resolved conflict again. Looks to be ready to merged still.

**Pull request merged**
