### PR TITLE
Generate TRCs in PEM format

### PR DESCRIPTION
**Pull request by matzf**
Change the data format of the TRCs from DER to PEM, both in the
generated configuration and in the internal representation in the DB.
Add a data migration to convert all existing TRCs.

Previously, we've generated the TRCs in DER format as this is currently
the default output format of `scion-pki trcs combine`. The (binary) DER
data was stored base64-encoded in the text database field.

According to the Anapayans working on this, the PEM format is should
generally be preferred, and it should become the default format for TRCs
eventually.

The practical motivation for the change is this; the CS persists any
TRCs fetched "over the wire" not only in its sqlite DB, but it also
writes them back to the configuration directory, in PEM format. As our
configuration has up to now contained TRCs in DER, installing updated
configuration using `scionlab-config` after the CS wrote such a TRC file
would lead to an apparent file conflict. Using PEM in our configuration
avoids this.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/406)

### CODE REVIEW

**Review by juagargi — COMMENTED** [review]
Have you tried to update a running existing host? I'm concerned about the trc files in `certs` (in my `17-ffaa:1:1` AS I have both PEM and raw DER files).

> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/406#-:-MthNkCx0HTLL5LgGyH1:b5v7bku)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by matzf — COMMENTED** [review]
Having the mixed PEM and DER files in `certs` is exactly the problem that this PR is addressing; the TRCs written by the CS are PEM, the ones from our configuration are DER. After this change, everything will be PEM.

While updating, `scionlab-config` should not complain about edit conflicts, as all existing files match either the expected old version (DER) or the new version (PEM).

I have tested the update with our automated upgrade test. I'll run another test explicitly checking the case with mixed file formats.

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/406#-:-MthQdWNAoGXJU1bFaMh:b-xszwjh)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)

**Review by juagargi — APPROVED** [review]
Yep. my concern is about the update finding issues with old DER files. Once you test a case with mixed DER and PEM files, I think we should be good to go.

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/406#-:-Mth_NR88hrWBaBLi5Bu:b-x5xt7i)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)

**Review by matzf — COMMENTED** [review]
Works as expected. Tested it in one of my own user ASes with an updated configuration tarball generated from a local clone of the coordinator:

Log:
```
vagrant@scionlab-ffaa-1-106:~$ file /etc/scion/certs/*
/etc/scion/certs/ISD16-B1-S1.trc: data
/etc/scion/certs/ISD16-B1-S2.trc: ASCII text
/etc/scion/certs/ISD17-B1-S1.trc: data
/etc/scion/certs/ISD17-B1-S2.trc: ASCII text
/etc/scion/certs/ISD17-B1-S3.trc: ASCII text
/etc/scion/certs/ISD18-B1-S1.trc: data
/etc/scion/certs/ISD18-B1-S2.trc: ASCII text
/etc/scion/certs/ISD19-B1-S1.trc: data
/etc/scion/certs/ISD19-B1-S2.trc: data
/etc/scion/certs/ISD19-B1-S3.trc: data
/etc/scion/certs/ISD19-B1-S4.trc: data
/etc/scion/certs/ISD20-B1-S1.trc: data
/etc/scion/certs/ISD20-B1-S2.trc: ASCII text
/etc/scion/certs/ISD21-B1-S1.trc: data
/etc/scion/certs/ISD22-B1-S1.trc: data
/etc/scion/certs/ISD25-B1-S1.trc: data
/etc/scion/certs/ISD26-B1-S1.trc: data
/etc/scion/certs/ISD26-B1-S2.trc: data

vagrant@scionlab-ffaa-1-106:~$ sudo scionlab-config --tar /vagrant/19-ffaa_1_106__127.0.0.1_v27.tar.gz
Created symlink /etc/systemd/system/scionlab.target.wants/scion-border-router@br-1.service → /lib/systemd/system/scion-border-router@.service.
Created symlink /etc/systemd/system/scionlab.target.wants/scion-control-service@cs-1.service → /lib/systemd/system/scion-control-service@.service.
Created symlink /etc/systemd/system/scionlab.target.wants/scion-colibri-service@co-1.service → /lib/systemd/system/scion-colibri-service@.service.
Created symlink /etc/systemd/system/scionlab.target.wants/scion-daemon.service → /lib/systemd/system/scion-daemon.service.
Created symlink /etc/systemd/system/scionlab.target.wants/scion-dispatcher.service → /lib/systemd/system/scion-dispatcher.service.

vagrant@scionlab-ffaa-1-106:~$ file /etc/scion/certs/*
/etc/scion/certs/ISD16-B1-S1.trc: ASCII text
/etc/scion/certs/ISD16-B1-S2.trc: ASCII text
/etc/scion/certs/ISD17-B1-S1.trc: ASCII text
/etc/scion/certs/ISD17-B1-S2.trc: ASCII text
/etc/scion/certs/ISD17-B1-S3.trc: ASCII text
/etc/scion/certs/ISD18-B1-S1.trc: ASCII text
/etc/scion/certs/ISD18-B1-S2.trc: ASCII text
/etc/scion/certs/ISD19-B1-S1.trc: ASCII text
/etc/scion/certs/ISD19-B1-S2.trc: ASCII text
/etc/scion/certs/ISD19-B1-S3.trc: ASCII text
/etc/scion/certs/ISD19-B1-S4.trc: ASCII text
/etc/scion/certs/ISD20-B1-S1.trc: ASCII text
/etc/scion/certs/ISD20-B1-S2.trc: ASCII text
/etc/scion/certs/ISD21-B1-S1.trc: ASCII text
/etc/scion/certs/ISD21-B1-S2.trc: ASCII text
/etc/scion/certs/ISD22-B1-S1.trc: ASCII text
/etc/scion/certs/ISD22-B1-S2.trc: ASCII text
/etc/scion/certs/ISD25-B1-S1.trc: ASCII text
/etc/scion/certs/ISD25-B1-S2.trc: ASCII text
/etc/scion/certs/ISD26-B1-S1.trc: ASCII text
/etc/scion/certs/ISD26-B1-S2.trc: ASCII text
/etc/scion/certs/ISD26-B1-S3.trc: ASCII text

vagrant@scionlab-ffaa-1-106:~$ # check that things are still working correctly
vagrant@scionlab-ffaa-1-106:~$ scion showpaths 17-ffaa:0:1108
Available paths to 17-ffaa:0:1108
[0] Hops: [19-ffaa:1:106 1>66 19-ffaa:0:1303 1>5 19-ffaa:0:1301 7>9 17-ffaa:0:1108] MTU: 1472 NextHop: 127.0.0.1:30001 Status: alive LocalIP: 127.0.0.1
[...] (everything looking normal) 
```

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/406#-:-Mtha8P767dzxo89uOo6:b-eu42a3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)

**Review by juagargi — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/406#-:-MthdAAp6-XGTWMiQ0TU:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)

**Pull request merged**
