### PR TITLE
add a link to our ICNP2020 infra node registration form

### PR DESCRIPTION
**Pull request by juagargi**
On the occasion of the ICNP2020, adding a link to the registration form to join our infrastructure.
~~This change should be temporary, and removed after the ending of ICNP2020.~~

This change is no longer temporary.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/311)

### CODE REVIEW

**Review by FR4NK-W — APPROVED** [review]

**Review by juagargi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/311)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @matzf)

___
*[scionlab/templates/scionlab/home.html, line 25 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/311#-MJWEO7wEb9i9dtr2Ue3:-MJXbxk6CMbY3Xi5Y5NP:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/97848f217fee61d5ea435243ed5a9d0eb6c579f6/scionlab/templates/scionlab/home.html#L25)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Instead of the `br`'s,  add margin to the top:
...><...><
`<p class="mt-5">If you arrived here from ICNP 2020, and would like to join the SCIONLab infrastructure, please sign up using this form:</p>`
</blockquote></details>

Done.
___
*[scionlab/templates/scionlab/home.html, line 26 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/311#-MJWDUgM3m84R3la4Kdn:-MJXcOD93rAZ-HNZhhr3:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/97848f217fee61d5ea435243ed5a9d0eb6c579f6/scionlab/templates/scionlab/home.html#L26)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Mark as an external link thingy?

```
<a ...><span class="fa fa-external-link d-none d-sm-inline"></span> ICNP 2020 Form</a>
```
</blockquote></details>

Done.
___
*[scionlab/templates/scionlab/home.html, line 27 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/311#-MJWCITY5O8p8AAMkgM0:-MJXcQqrDqceqETYOnER:b3jjuo6) ([raw file](https://github.com/netsec-ethz/scionlab/blob/97848f217fee61d5ea435243ed5a9d0eb6c579f6/scionlab/templates/scionlab/home.html#L27)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Is intentionally hidden for logged in users? Otherwise, move down here.
</blockquote></details>

I thought to hide it, yes. Do you think it is confusing?

**Review by FR4NK-W — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/311)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @matzf)

___
*[scionlab/templates/scionlab/home.html, line 26 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/311#-MJWDUgM3m84R3la4Kdn:-MJXbPF4631zINHpvwwB:b-5y458b) ([raw file](https://github.com/netsec-ethz/scionlab/blob/97848f217fee61d5ea435243ed5a9d0eb6c579f6/scionlab/templates/scionlab/home.html#L26)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Are we tracking the source of the traffic to the form?
Otherwise we could also additionally add the `noreferrer` attribute to the link (and nofollow? since it is an outgoing link).

**Review by FR4NK-W — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/311)* status: all files reviewed, 2 unresolved discussions (waiting on @juagargi and @matzf)

___
*[scionlab/templates/scionlab/home.html, line 27 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/311#-MJWCITY5O8p8AAMkgM0:-MJXctr8CwEW1QGdRFhx:b-vulwbs) ([raw file](https://github.com/netsec-ethz/scionlab/blob/97848f217fee61d5ea435243ed5a9d0eb6c579f6/scionlab/templates/scionlab/home.html#L27)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

I thought to hide it, yes. Do you think it is confusing?
</blockquote></details>

It might prevent the 'ideal workflow', where people interested in SCIONLab first try it out as a userAS and then decide to 'upgrade' to a infrastructure AS (and still need a PC Engines device).

**Review by FR4NK-W — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/311)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)

**Review by matzf — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/311)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by matzf — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/311)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
