### PR TITLE
Increase default log level from debug to info

### PR DESCRIPTION
**Pull request by cmeury**
Goals:

* Reduce log volumes on SCIONLab infrastructure nodes to avoid disk space issues (on top of aggressive log rotate & compress)
* Reduce unexpectedly verbose output on user AS configurations

(re-created PR, older discussion in #342)

Also, providing a mach binary to run unit tests and scripts on MacOS, behind a shim script to select the correct binary.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/349)

### CODE REVIEW

**Review by matzf — CHANGES_REQUESTED** [review]
Changes for the log level and integration tests LGTM. :+1: 
And another :+1: for building the correct version of the tool. 

> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/349#-:-MOhGKwb14NonsTvQ43s:b6vfq2q)* status: all files reviewed, 5 unresolved discussions (waiting on @cmeury)

___
*[static_bin/Dockerfile, line 15 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/349#-MOhDkbo3nuTR1J3lZQ_:-MOhDkbo3nuTR1J3lZQa:blmg9v2) ([raw file](https://github.com/netsec-ethz/scionlab/blob/5b6de707b51de16e93321ee6d7c029af50b2006b/static_bin/Dockerfile#L15)):*
> ```Dockerfile
> 
> RUN startup_version=$(git describe --tags --always)-scionlab && \
>     go build -ldflags="-s -w -X github.com/scionproto/scion/go/lib/env.StartupVersion=$startup_version" \
> ```

While we're at it, let's specify GOOS and GOARcH explicitly here too, please.
___
*[static_bin/scion-pki, line 1 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/349#-MOh8SuJ6sRjnqx0p8uo:-MOh8SuJ6sRjnqx0p8up:b-m5mt3g) ([raw file](https://github.com/netsec-ethz/scionlab/blob/5b6de707b51de16e93321ee6d7c029af50b2006b/static_bin/scion-pki#L1)):*
> ```
> #!/bin/bash
> ```

If we already make this portable, we should probably not use bash, but full-on posix shell (running this e.g. on alpine with busybox is not such an absurd idea).

```sh
#!/bin/sh
```
___
*[static_bin/scion-pki, line 4 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/349#-MOh7nvi17TPKGr36-9A:-MOh7nvk2B07Qj6Z6mKT:b4pk4mo) ([raw file](https://github.com/netsec-ethz/scionlab/blob/5b6de707b51de16e93321ee6d7c029af50b2006b/static_bin/scion-pki#L4)):*
> ```
> 
> # get script location, thanks: https://stackoverflow.com/a/246128/28578
> DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
> ```

Simple `DIR=$(dirname "$0")` may be better -- we don't need an absolute path, we don't really care about symlinks, this will not be `source`ed, etc. And this is actually somewhat more portable (see comment on shebang).
___
*[static_bin/scion-pki, line 6 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/349#-MOh8H5O2oWeuvx-8apF:-MOh8H5O2oWeuvx-8apG:bw3qhtx) ([raw file](https://github.com/netsec-ethz/scionlab/blob/5b6de707b51de16e93321ee6d7c029af50b2006b/static_bin/scion-pki#L6)):*
> ```
> DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
> 
> unameOut="$(uname -s)"
> ```

If we do this, we should probably also include the machine architecture in the check and in the name of the binary ( ("Darwin arm64" is probably next ;)) 
`uname -s -m`, see table on [wikipedia](https://en.wikipedia.org/wiki/Uname).
___
*[static_bin/scion-pki, line 9 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/349#-MOh7vTx2Zk5vxiBiCm-:-MOh7vTx2Zk5vxiBiCm0:b-fpll7j) ([raw file](https://github.com/netsec-ethz/scionlab/blob/5b6de707b51de16e93321ee6d7c029af50b2006b/static_bin/scion-pki#L9)):*
> ```
> case "${unameOut}" in
>     Linux*)     ${DIR}/scion-pki-linux "$@" ;;
>     Darwin*)    ${DIR}/scion-pki-mac "$@" ;;
> ```

Both lines:
- missing quotes around DIR: `"${DIR}"/scion-pki-[...]`
- should `exec`: `exec "${DIR}"/scion-pki-...`

**Comment by cmeury** [comment]
___
*[static_bin/Dockerfile, line 15 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/349#-MOhDkbo3nuTR1J3lZQ_:-MOkn1GC4w_HCxZQpzps:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/5b6de707b51de16e93321ee6d7c029af50b2006b/static_bin/Dockerfile#L15)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

While we're at it, let's specify GOOS and GOARcH explicitly here too, please.
</blockquote></details>

Done.

**Review by cmeury — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/349)* status: all files reviewed, 5 unresolved discussions (waiting on @matzf)

___
*[static_bin/scion-pki, line 1 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/349#-MOh8SuJ6sRjnqx0p8uo:-MOkpM0-4-KmVXcJBL9i:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/5b6de707b51de16e93321ee6d7c029af50b2006b/static_bin/scion-pki#L1)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

If we already make this portable, we should probably not use bash, but full-on posix shell (running this e.g. on alpine with busybox is not such an absurd idea).

```sh
#!/bin/sh
```
</blockquote></details>

Done.
___
*[static_bin/scion-pki, line 4 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/349#-MOh7nvi17TPKGr36-9A:-MOkpXv-CTS4LoncoVNL:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/5b6de707b51de16e93321ee6d7c029af50b2006b/static_bin/scion-pki#L4)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Simple `DIR=$(dirname "$0")` may be better -- we don't need an absolute path, we don't really care about symlinks, this will not be `source`ed, etc. And this is actually somewhat more portable (see comment on shebang).
</blockquote></details>

Done.
___
*[static_bin/scion-pki, line 6 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/349#-MOh8H5O2oWeuvx-8apF:-MOku0nG1mFIhRnfxHg4:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/5b6de707b51de16e93321ee6d7c029af50b2006b/static_bin/scion-pki#L6)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

If we do this, we should probably also include the machine architecture in the check and in the name of the binary ( ("Darwin arm64" is probably next ;)) 
`uname -s -m`, see table on [wikipedia](https://en.wikipedia.org/wiki/Uname).
</blockquote></details>

Done.
___
*[static_bin/scion-pki, line 9 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/349#-MOh7vTx2Zk5vxiBiCm-:-MOku1tlAiRV-1RQc5PC:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/5b6de707b51de16e93321ee6d7c029af50b2006b/static_bin/scion-pki#L9)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Both lines:
- missing quotes around DIR: `"${DIR}"/scion-pki-[...]`
- should `exec`: `exec "${DIR}"/scion-pki-...`
</blockquote></details>

Done.

**Review by matzf — APPROVED** [review]
:lgtm_strong: :

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/349#-:-MOl2qh01dw4dU5d06qj:b-yncq55)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[static_bin/Dockerfile, line 15 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/349#-MOhDkbo3nuTR1J3lZQ_:-MOl1jX1DXBpNfUUdFKt:bdbb9vi) ([raw file](https://github.com/netsec-ethz/scionlab/blob/5b6de707b51de16e93321ee6d7c029af50b2006b/static_bin/Dockerfile#L15)):*
<details><summary><i>Previously, cmeury (Cedric Meury) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice! :100:

**Pull request merged**
