### PR TITLE
Static port assignment for ctrl/internal port

### LINKED ISSUE #318: Port clashes and PortMap
Our `PortMap` is currently used to avoid port clashes when creating border routers.
We have found a problem (fixed by #317 ) where there was a clash in a host, between the control service internal port `CS_PORT` and a border router internal port that reached up to the same value (30254 at the moment of this ticket).
Check the following:
- could we define three valid ranges for the border routers?
- also change the value of the ports from other services that sit in these ranges (e.g. `SD_TCP_PORT = 30255`)? Even if they were TCP, so debugging is easier.
- take care of other possible port clashes, like Prometheus ports for BRs with `SD_PROM_PORT`

### PR DESCRIPTION
**Pull request by matzf**
Use a statically defined port scheme for control, internal and metrics
ports, given by a base port + instance id.
The choice of the base port(s) allows for up to 40 border router
instances, before clashing with the dispatcher port.

Depends on #346
Fixes #318 

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/347)

### CODE REVIEW

**Review by juagargi — APPROVED** [review]
I just left a question

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/347#-:-MOGAptTCZk81QpiRKTF:br3hpfq)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)

___
*[scionlab/defines.py, line 32 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/347#-MOGAbVx0qbaJpMtykSY:-MOGAbVx0qbaJpMtykSZ:bnhrbab) ([raw file](https://github.com/netsec-ethz/scionlab/blob/3581a2608bae7d1710578b2548acc27f3542fb99/scionlab/defines.py#L32)):*
> ```Python
> # Notably, this scheme starts at lower numbers to allow up to 40 routers before collision with the
> # range used for the dispatcher (30041).
> BR_INTERNAL_PORT_BASE = 30000    # UDP/IP, internal_ip:port
> ```

could we move these BASE ports to a different "window"? e.g. 31000-32000

**Review by juagargi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/347)* status: 19 of 20 files reviewed, 1 unresolved discussion (waiting on @juagargi and @matzf)

___
*[scionlab/migrations/0010_remove_router_internal_port_ctrl_port.py, line 7 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/347#-MO_pUhyDwMG4zMxbCZD:-MO_pUhyDwMG4zMxbCZE:br8z1jb) ([raw file](https://github.com/netsec-ethz/scionlab/blob/b18d6e97048d807f8eb2bca5d666faf23646f68d/scionlab/migrations/0010_remove_router_internal_port_ctrl_port.py#L7)):*
> ```Python
> 
> def bump_config(apps, schema_editor):
>     # Host = apps.get_model('scionlab', 'Host')
> ```

commented out

**Review by juagargi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/347#-:-MO_tDG23aOGggSEij2C:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/347)* status: all files reviewed, 1 unresolved discussion (waiting on @juagargi)

___
*[scionlab/migrations/0010_remove_router_internal_port_ctrl_port.py, line 7 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/347#-MO_pUhyDwMG4zMxbCZD:-MO_tKle29Ddf6kwzqM3:b-h7voz8) ([raw file](https://github.com/netsec-ethz/scionlab/blob/b18d6e97048d807f8eb2bca5d666faf23646f68d/scionlab/migrations/0010_remove_router_internal_port_ctrl_port.py#L7)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

commented out
</blockquote></details>

Good catch. Silly me for copy-pasting without checking. We have `use_in_migrations` enabled for the `HostManager`, so we can use the `get_model` for this, as we had previously done. Unclear why this was not in the migration 8 where I copied this from... No biggie, I guess.

**Pull request merged**
