### PR TITLE
Update Django version

### PR DESCRIPTION
**Pull request by FR4NK-W**
Update Django minor version and other pip requirements

- - -
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/426)

### CODE REVIEW

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/426)* status: 0 of 4 files reviewed, all discussions resolved / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`requirements.txt` line 9 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/426#-NC4ByF66da3mc-asuOR:-NC4ByF66da3mc-asuOS:b-2rq49h) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e360044aa9451a3397ecdcfd21d7f22ca0066c9c/requirements.txt#L9)):*
> ```help
> asgiref==3.5.2 \
>     --hash=sha256:1d2880b792ae8757289136f1db2b7b99100ce959b2aa57fd69dab783d05afac4 \
>     --hash=sha256:4a29362a6acebe09bf1d6640db38c1dc3d9217c68e6f9f6204d72667fc19a424
> ```

This version is not compatible with python 3.6, and I think this is what's causing the problems. If you run pip-compile on a python 3.6, it seems to only update django and not any of the other dependencies.

**Comment by FR4NK-W** [comment]
@matzf  Thanks for the hint, but even running pip-compile on the exact same version the CI image is using does not seem to work:
`circleci@adc0672f53f4:/tmp$ python --version                                                                                                                             
Python 3.6.13                                                                                                                                                            
circleci@adc0672f53f4:/tmp$ head -n1 requirements.in                                                                                                                     
Django>=3.2.15,<4.0                                                                                                                                                      
circleci@adc0672f53f4:/tmp$ pip-compile --generate-hashes --output-file=requirements.txt requirements.in                                                                 
  ERROR: Could not find a version that satisfies the requirement asgiref==3.5.2 (from django==3.2.15->-r requirements.in (line 1)) (from versions: 0.8, 0.9, 0.9.1[0/802]0, 0.11.0, 0.11.1, 0.11.2, 0.12.0, 0.12.1, 0.13.0, 0.13.2, 0.13.3, 0.14.0, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.1.2, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.2.0, 2.3.0, 2.3.1, 2.3.2, 3.0.0, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.2.4, 3.2.5, 3.2.6, 3.2.7, 3.2.8, 3.2.9, 3.2.10, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.4.0, 3.4.1)
Traceback (most recent call last):                                                                                              
  File "/home/circleci/.pyenv/versions/3.6.13/bin/pip-compile", line 11, in <module>                                                                                         sys.exit(cli())                                                                 
  File "/home/circleci/.pyenv/versions/3.6.13/lib/python3.6/site-packages/click/core.py", line 1128, in __call__                
    return self.main(*args, **kwargs)                                                                                                                       
  File "/home/circleci/.pyenv/versions/3.6.13/lib/python3.6/site-packages/click/core.py", line 1053, in main                    
    rv = self.invoke(ctx)                                                                                                                                   
  File "/home/circleci/.pyenv/versions/3.6.13/lib/python3.6/site-packages/click/core.py", line 1395, in invoke                  
    return ctx.invoke(self.callback, **ctx.params)                                                                                                          
  File "/home/circleci/.pyenv/versions/3.6.13/lib/python3.6/site-packages/click/core.py", line 754, in invoke                                    
    return __callback(*args, **kwargs)                                                                                                          
  File "/home/circleci/.pyenv/versions/3.6.13/lib/python3.6/site-packages/click/decorators.py", line 26, in new_func                          
    return f(get_current_context(), *args, **kwargs)                                                                                          
  File "/home/circleci/.pyenv/versions/3.6.13/lib/python3.6/site-packages/piptools/scripts/compile.py", line 466, in cli                      
    results = resolver.resolve(max_rounds=max_rounds)                                                                                                       
  File "/home/circleci/.pyenv/versions/3.6.13/lib/python3.6/site-packages/piptools/resolver.py", line 175, in resolve                         
    has_changed, best_matches = self._resolve_one_round()                                                                                                   
  File "/home/circleci/.pyenv/versions/3.6.13/lib/python3.6/site-packages/piptools/resolver.py", line 319, in _resolve_one_round                 
    their_constraints.extend(self._iter_dependencies(best_match))                                                                                           
  File "/home/circleci/.pyenv/versions/3.6.13/lib/python3.6/site-packages/piptools/resolver.py", line 428, in _iter_dependencies                            
    dependencies = self.repository.get_dependencies(ireq)                                                                                                   
  File "/home/circleci/.pyenv/versions/3.6.13/lib/python3.6/site-packages/piptools/repositories/local.py", line 79, in get_dependencies                     
    return self.repository.get_dependencies(ireq)                                                                                                           
  File "/home/circleci/.pyenv/versions/3.6.13/lib/python3.6/site-packages/piptools/repositories/pypi.py", line 237, in get_dependencies                                      download_dir, ireq, wheel_cache                                                                                                                                        File "/home/circleci/.pyenv/versions/3.6.13/lib/python3.6/site-packages/piptools/repositories/pypi.py", line 199, in resolve_reqs                                          results = resolver._resolve_one(reqset, ireq)                                   
  File "/home/circleci/.pyenv/versions/3.6.13/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 379, in _resolve_one                            dist = self._get_dist_for(req_to_install)                                                                                                                              File "/home/circleci/.pyenv/versions/3.6.13/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 331, in _get_dist_for                           self._populate_link(req)                                                                                                                                               File "/home/circleci/.pyenv/versions/3.6.13/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 300, in _populate_link                          req.link = self._find_requirement_link(req)                                     
  File "/home/circleci/.pyenv/versions/3.6.13/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 266, in _find_requirement_link                  best_candidate = self.finder.find_requirement(req, upgrade)                                                                                                            File "/home/circleci/.pyenv/versions/3.6.13/lib/python3.6/site-packages/pip/_internal/index/package_finder.py", line 910, in find_requirement                              "No matching distribution found for {}".format(req)                                                                                                     
pip._internal.exceptions.DistributionNotFound: No matching distribution found for asgiref==3.5.2 (from django==3.2.15->-r requirements.in (line 1))                      circleci@adc0672f53f4:/tmp$`

>This version is not compatible with python 3.6, and I think this is what's causing the problems. If you run pip-compile on a python 3.6, it seems to only update django and not any of the other dependencies.

Could you share for which exact python3.6 minor version and which version of pip-tools (6.4.0 produces the output above)  it only updated django for you?

**Review by matzf — COMMENTED** [review]
python 3.6.9
pip-compile 6.4.0 (and same with 6.0.1)


Not sure what's going on, but I've just tested this in a python 3.6.13 docker container as well, with the same result.
```
matzf@thumper:~/dev/scionlab$ docker run -ti -v `realpath .`:/project python:3.6.13 /bin/bash
root@b9b7d8d9369d:/# pip install -U pip setuptools wheel pip-tools
....
Successfully installed click-8.0.4 importlib-metadata-4.8.3 pep517-0.13.0 pip-21.3.1 pip-tools-6.4.0 setuptools-59.6.0 tomli-1.2.3 typing-extensions-4.1.1 wheel-0.37.1 zipp-3.6.0

root@b9b7d8d9369d:/# cd /project/
root@b9b7d8d9369d:/project# pip-compile --generate-hashes --output-file=requirements.txt requirements.in
....

root@b9b7d8d9369d:/project# git diff
diff --git a/requirements.in b/requirements.in
index 2318bcc..57e4250 100644
--- a/requirements.in
+++ b/requirements.in
@@ -1,4 +1,4 @@
-Django>=3
+Django>=3.2.15,<4.0
 cryptography
 django-crispy-forms>=1.9.0
 django-extensions
diff --git a/requirements.txt b/requirements.txt
index 541e5c9..08c4a94 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,5 +1,5 @@
 #
-# This file is autogenerated by pip-compile
+# This file is autogenerated by pip-compile with python 3.6
 # To update, run:
 #
 #    pip-compile --generate-hashes --output-file=requirements.txt requirements.in
@@ -75,6 +75,13 @@ cryptography==3.4.7 \
     --hash=sha256:eb8cc2afe8b05acbd84a43905832ec78e7b3873fb124ca190f574dca7389a87d \
     --hash=sha256:ee77aa129f481be46f8d92a1a7db57269a2f23052d5f2433b4621bb457081cc9
     # via -r requirements.in
+django==3.2.15 \
+    --hash=sha256:115baf5049d5cf4163e43492cdc7139c306ed6d451e7d3571fe9612903903713 \
+    --hash=sha256:f71934b1a822f14a86c9ac9634053689279cd04ae69cb6ade4a59471b886582b
+    # via
+    #   -r requirements.in
+    #   django-extensions
+    #   django-registration
 django-crispy-forms==1.11.2 \
     --hash=sha256:3db71ab06d17ec9d0195c086d3ad454da300ac268752ac3a4f63d72f7a490254 \
     --hash=sha256:88efa857ce6111bd696cc4f74057539a3456102fe9c3a3ece8868e1e4579e70a
@@ -95,13 +102,6 @@ django-registration==3.1.2 \
     --hash=sha256:c9985f9ffd123534026bf5f39adb0b48fd7bf930b965f27f9a487d135f377ac6 \
     --hash=sha256:dde525b08880da1d72b556f19dfd1c6588233a43f8bc354481f2d3e8896c44f8
     # via -r requirements.in
-django==3.2.13 \
-    --hash=sha256:6d93497a0a9bf6ba0e0b1a29cccdc40efbfc76297255b1309b3a884a688ec4b6 \
-    --hash=sha256:b896ca61edc079eb6bbaa15cf6071eb69d6aac08cce5211583cfb41515644fdf
-    # via
-    #   -r requirements.in
-    #   django-extensions
-    #   django-registration
 graphviz==0.16 \
     --hash=sha256:3cad5517c961090dfc679df6402a57de62d97703e2880a1a46147bb0dc1639eb \
     --hash=sha256:d2d25af1c199cad567ce4806f0449cb74eb30cf451fd7597251e1da099ac6e57
```

No clue what's happening here. :confused: 

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/426#-:-NC4N4WK-P0KMlQBQqW3:bo62fjx)* status: 0 of 4 files reviewed, all discussions resolved / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

**Comment by FR4NK-W** [comment]
Well, that was 'fun'. Looks like a bug in pip-compile.
I don't think it is worth to investigate for an old version of python3.6 where the difference comes from and why it only occurs in the circleci python image.

@matzf  Do you want to have a look if you are happy with how the dependencies were resolved?

The CS in the integration test is now complaining about a missing /etc/scion/staticInfoConfig.json , but that's unrelated.
(Running the circleci jobs with a console attached still doesn't work like it used to, and this clearly isn't the right solution: https://discuss.circleci.com/t/unable-to-ssh-into-machine-executor-environment/45358/2)

**Comment by FR4NK-W** [comment]
@matzf ^ rebased

**Review by matzf — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/426#-:-NCOml867pbuhxY19G-M:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
