### PR TITLE
Cache Git LFS files in CI to save bandwith

### PR DESCRIPTION
**Pull request by cmeury**
The two binaries in `static_bin` amount to 42MB. The standard LFS bandwith limit of 1GB is quickly exceeded by a low number of LFS pull operations. This PR adds caching of these files based on their LFS IDs.

YAML does not allow to use anchors with lists, so the items have to be included separately. Still better than repeating?

### CircleCI Illustration of successful cache retrieval

It's saying 14 MB because that's the size of the compressed two files.

image

This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/350)

### CODE REVIEW

**Comment by FR4NK-W** [comment]
>YAML does not allow to use anchors with lists, so the items have to be included separately. Still better than repeating?

The `basic` and `integration` jobs are run in parallel, the job `integration` is not going to store a fresher version, so you could drop the duplicate hash computation and `<<: *save_lfs_cache` there.
You could even delay the integration job by some arbitrary delay to prevent both jobs to hit a stale cache at the same time and fetch the files in parallel.
Reduce the fetches by a further x2 :rocket:

**Comment by cmeury** [comment]
> The `basic` and `integration` jobs are run in parallel, the job `integration` is not going to store a fresher version, so you could drop the duplicate hash computation and `<<: *save_lfs_cache` there.

@FR4NK-W This will help only in the rare instances when the binaries are updated, and sometimes you want to run individual failed jobs separately. I don't think it's worth making this more complicated?

**Review by juagargi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/350#-:-MQSRRMD8TBJ-EQg1EtH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by FR4NK-W — COMMENTED** [review]
:thumbsup: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/350#-:-MQluIyf1AZCcyY1EvK5:b4c9lyr)* status: all files reviewed, 1 unresolved discussion / 0 of 1 LGTMs obtained, and 1 stale / 0 of 1 approvals obtained

___
*[.circleci/config.yml, line 36 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/350#-MQls1tuAj1zyoQl5lu6:-MQls1tuAj1zyoQl5lu7:bkx8m2y) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2cb09ac70a62153b35bba2e501b53b057dd1ba28/.circleci/config.yml#L36)):*
> ```
> # this command needs this environment variable: GIT_LFS_SKIP_SMUDGE: 1
> ```

Setting the environment variable for the step that needs it https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-step instead of setting it globally for the job would make clearer which step needs it.

**Comment by cmeury** [comment]
___
*[.circleci/config.yml, line 36 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/350#-MQls1tuAj1zyoQl5lu6:-MQm-19U0hEiFSvqRQBa:b-4jjjx2) ([raw file](https://github.com/netsec-ethz/scionlab/blob/17ee6169768ff5996d847689129dd6bdf8d19cb1/.circleci/config.yml#L36)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

> ```
> # this command needs this environment variable: GIT_LFS_SKIP_SMUDGE: 1
> ```

Setting the environment variable for the step that needs it https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-step instead of setting it globally for the job would make clearer which step needs it.
</blockquote></details>

Good idea, but unfortunately we [cannot modify the checkout command](https://support.circleci.com/hc/en-us/articles/115015659247-How-do-I-modify-the-checkout-step-). I tried it myself, no luck.

An option would be to spell out the git command, but I'd prefer the convenient short-hand.

**Review by matzf — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/350)* status: all files reviewed, 1 unresolved discussion / 0 of 1 LGTMs obtained, and 1 stale / 0 of 1 approvals obtained

**Review by FR4NK-W — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/350)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
